package com.wry.dao;

import com.wry.model.BarClassify;
import java.math.BigDecimal;

public interface BarClassifyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY
     *
     * @mbggenerated Tue Aug 01 17:11:03 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY
     *
     * @mbggenerated Tue Aug 01 17:11:03 CST 2017
     */
    int insert(BarClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY
     *
     * @mbggenerated Tue Aug 01 17:11:03 CST 2017
     */
    int insertSelective(BarClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY
     *
     * @mbggenerated Tue Aug 01 17:11:03 CST 2017
     */
    BarClassify selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY
     *
     * @mbggenerated Tue Aug 01 17:11:03 CST 2017
     */
    int updateByPrimaryKeySelective(BarClassify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY
     *
     * @mbggenerated Tue Aug 01 17:11:03 CST 2017
     */
    int updateByPrimaryKey(BarClassify record);
}