package com.wry.dao;

import com.wry.annotation.MybatisDateBaseOracleOne;
import com.wry.model.BarClassifyUrl;
import java.math.BigDecimal;

@MybatisDateBaseOracleOne
public interface BarClassifyUrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY_URL
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY_URL
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    int insert(BarClassifyUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY_URL
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    int insertSelective(BarClassifyUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY_URL
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    BarClassifyUrl selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY_URL
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    int updateByPrimaryKeySelective(BarClassifyUrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table BAR_CLASSIFY_URL
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    int updateByPrimaryKey(BarClassifyUrl record);
}