package com.wry.model;

import java.math.BigDecimal;
import java.util.Date;

public class BarClassifyUrl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR_CLASSIFY_URL.ID
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR_CLASSIFY_URL.BAR_CLASSIFY_ID
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    private BigDecimal barClassifyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR_CLASSIFY_URL.BAR_URL_NAME
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    private String barUrlName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR_CLASSIFY_URL.BAR_URL_ADDRESS
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    private String barUrlAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR_CLASSIFY_URL.DATE_CREATED
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    private Date dateCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR_CLASSIFY_URL.ID
     *
     * @return the value of BAR_CLASSIFY_URL.ID
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR_CLASSIFY_URL.ID
     *
     * @param id the value for BAR_CLASSIFY_URL.ID
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR_CLASSIFY_URL.BAR_CLASSIFY_ID
     *
     * @return the value of BAR_CLASSIFY_URL.BAR_CLASSIFY_ID
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public BigDecimal getBarClassifyId() {
        return barClassifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR_CLASSIFY_URL.BAR_CLASSIFY_ID
     *
     * @param barClassifyId the value for BAR_CLASSIFY_URL.BAR_CLASSIFY_ID
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public void setBarClassifyId(BigDecimal barClassifyId) {
        this.barClassifyId = barClassifyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR_CLASSIFY_URL.BAR_URL_NAME
     *
     * @return the value of BAR_CLASSIFY_URL.BAR_URL_NAME
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public String getBarUrlName() {
        return barUrlName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR_CLASSIFY_URL.BAR_URL_NAME
     *
     * @param barUrlName the value for BAR_CLASSIFY_URL.BAR_URL_NAME
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public void setBarUrlName(String barUrlName) {
        this.barUrlName = barUrlName == null ? null : barUrlName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR_CLASSIFY_URL.BAR_URL_ADDRESS
     *
     * @return the value of BAR_CLASSIFY_URL.BAR_URL_ADDRESS
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public String getBarUrlAddress() {
        return barUrlAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR_CLASSIFY_URL.BAR_URL_ADDRESS
     *
     * @param barUrlAddress the value for BAR_CLASSIFY_URL.BAR_URL_ADDRESS
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public void setBarUrlAddress(String barUrlAddress) {
        this.barUrlAddress = barUrlAddress == null ? null : barUrlAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR_CLASSIFY_URL.DATE_CREATED
     *
     * @return the value of BAR_CLASSIFY_URL.DATE_CREATED
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR_CLASSIFY_URL.DATE_CREATED
     *
     * @param dateCreated the value for BAR_CLASSIFY_URL.DATE_CREATED
     *
     * @mbggenerated Tue Aug 01 17:08:48 CST 2017
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
}