package com.wry.model;

import java.math.BigDecimal;
import java.util.Date;

public class BarClassify {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR_CLASSIFY.ID
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    private BigDecimal id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR_CLASSIFY.CLASSIFY_NAME
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    private String classifyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column BAR_CLASSIFY.DATE_CREATED
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    private Date dateCreated;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR_CLASSIFY.ID
     *
     * @return the value of BAR_CLASSIFY.ID
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR_CLASSIFY.ID
     *
     * @param id the value for BAR_CLASSIFY.ID
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR_CLASSIFY.CLASSIFY_NAME
     *
     * @return the value of BAR_CLASSIFY.CLASSIFY_NAME
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    public String getClassifyName() {
        return classifyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR_CLASSIFY.CLASSIFY_NAME
     *
     * @param classifyName the value for BAR_CLASSIFY.CLASSIFY_NAME
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    public void setClassifyName(String classifyName) {
        this.classifyName = classifyName == null ? null : classifyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column BAR_CLASSIFY.DATE_CREATED
     *
     * @return the value of BAR_CLASSIFY.DATE_CREATED
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    public Date getDateCreated() {
        return dateCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column BAR_CLASSIFY.DATE_CREATED
     *
     * @param dateCreated the value for BAR_CLASSIFY.DATE_CREATED
     *
     * @mbggenerated Tue Aug 01 17:06:30 CST 2017
     */
    public void setDateCreated(Date dateCreated) {
        this.dateCreated = dateCreated;
    }
}